# Generated by Django 5.1.5 on 2025-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap", models.CharField(max_length=50, unique=True)),
                ("descricao", models.CharField(max_length=255)),
                ("quantidade", models.IntegerField(blank=True, default=0, null=True)),
                ("unidade", models.CharField(blank=True, max_length=10, null=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiais",
            },
        ),
    ]
