# Generated by Django 5.1.5 on 2025-01-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="quantidade",
        ),
        migrations.RemoveField(
            model_name="material",
            name="unidade",
        ),
    ]
