# Generated by Django 5.1.5 on 2025-01-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0002_remove_material_quantidade_remove_material_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="quantidade_atual",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Movimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=7,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data", models.DateField()),
                ("rc", models.CharField(blank=True, max_length=50, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materiais.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento",
                "verbose_name_plural": "Movimentos",
            },
        ),
    ]
