# Generated by Django 5.1.5 on 2025-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0003_material_quantidade_atual_movimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ONT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap", models.CharField(max_length=50, unique=True)),
                (
                    "n_doc",
                    models.CharField(max_length=50, verbose_name="Número do Documento"),
                ),
                ("carga", models.CharField(max_length=50)),
                (
                    "nome_equipamento",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Equipamento"
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Série"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ONT",
                "verbose_name_plural": "ONTs",
                "ordering": ["-data_cadastro"],
            },
        ),
    ]
