# Generated by Django 5.1.5 on 2025-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0004_ont"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ont",
            name="sap",
            field=models.CharField(max_length=50),
        ),
    ]
